### ISSUE TITLE
cant run on 1.20.1

### ISSUE THREAD

**Issue by ocschoz** [Numelon-Softworks/ThreatenGL#4] opened 2024-05-15 04:55 UTC
The mod requires Architectury API with version 11.1.17 but for 1.20.1 the latest version is 9.2.14. Please have a look on this issue. Thank you for your effort on building the mod!!

**Comment by BrusselSprouts0** [comment] 2024-05-15 11:59
I have the same problem. Any version below 1.20.4 is incompatible due to it needing 11.1.17 of architectury

**Comment by Richy-Z** [comment] 2024-05-15 15:01
Hello!

Thank You for reporting this issue. I have updated the dependency requirements accordingly so that the mods actually work as intended and as advertised from 1.17.1 onwards.

A new release will be published on GitHub and Modrinth in around an hour. 🙂

**Comment by Richy-Z** [comment] 2024-05-15 17:12
This issue has been fixed in release 1.2.1-beta.2 of ThreatenGL.

The new releases with the fix are available on GitHub and Modrinth.
**Modrinth (Recommended)**: https://modrinth.com/mod/threatengl/versions
**GitHub**: https://github.com/Numelon-Softworks/ThreatenGL/releases/tag/1.2.1

**Comment by Richy-Z** [comment] 2024-05-15 17:12
This issue has been fixed in release 1.2.1-beta.2 of ThreatenGL. 😸

The new releases with the fix are available on GitHub and Modrinth.
**Modrinth (Recommended)**: https://modrinth.com/mod/threatengl/versions
**GitHub**: https://github.com/Numelon-Softworks/ThreatenGL/releases/tag/1.2.1

**Closed by Richy-Z** 2024-05-15 17:12 UTC
Labels: bug
